import { Inter } from 'next/font/google'

import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Layout/Header'
import clsx from 'clsx'
import { Footer } from '@/components/Layout/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'min-h-dvh')}>
        <Header />
        <div className="pt-[92px] lg:pt-[126px]">{children}</div>
        <Footer />
      </body>
    </html>
  )
}
